import React, { useState } from 'react';
import { ReactSearchAutocomplete } from 'react-search-autocomplete';
import '../css/searchbar.css'

function SearchBar({ onIngredientSearch }) {

    // set ingredients list to search from here, can also be fed into this component from outside
    // tutorial used here: https://www.dhiwise.com/post/how-to-build-react-search-bar-with-suggestions
    // much of it is very similar
    const [items, setItems] = useState([
      { id: 13, name: '5 Spice Powder' } ,
      { id: 14, name: 'Acorn Squash' } ,
      { id: 15, name: 'Adobo Sauce' } ,
      { id: 16, name: 'Agave Nectar' } ,
      { id: 17, name: 'Ahi Tuna' } ,
      { id: 18, name: 'Alfredo Pasta Sauce' } ,
      { id: 19, name: 'Almond Extract' } ,
      { id: 20, name: 'Almond Flour' } ,
      { id: 21, name: 'Almond Milk' } ,
      { id: 22, name: 'Almonds' } ,
      { id: 23, name: 'Amaretto' } ,
      { id: 24, name: 'Ancho Chiles' } ,
      { id: 25, name: 'Anchovies' } ,
      { id: 26, name: 'Andouille Sausage' } ,
      { id: 27, name: 'Angel Food Cake Mix' } ,
      { id: 28, name: 'Angel Hair Pasta' } ,
      { id: 29, name: 'Angostura Bitters' } ,
      { id: 30, name: 'Apple' } ,
      { id: 31, name: 'Apple Butter Spread' } ,
      { id: 32, name: 'Apple Cider' } ,
      { id: 33, name: 'Apple Juice' } ,
      { id: 34, name: 'Apple Pie Spice' } ,
      { id: 35, name: 'Apricot Preserves' } ,
      { id: 36, name: 'Apricots' } ,
      { id: 37, name: 'Arborio Rice' } ,
      { id: 38, name: 'Arrowroot Powder' } ,
      { id: 39, name: 'Artichoke Heart Quarters' } ,
      { id: 40, name: 'Artichokes' } ,
      { id: 41, name: 'Arugula' } ,
      { id: 42, name: 'Asafoetida' } ,
      { id: 43, name: 'Asafoetida Powder' } ,
      { id: 44, name: 'Asiago Cheese' } ,
      { id: 45, name: 'Asian Pear' } ,
      { id: 46, name: 'Asparagus Spears' } ,
      { id: 47, name: 'Avocado' } ,
      { id: 48, name: 'Avocado Oil' } ,
      { id: 49, name: 'Baby Bell Peppers' } ,
      { id: 50, name: 'Baby Bok Choy' } ,
      { id: 51, name: 'Baby Carrots' } ,
      { id: 52, name: 'Baby Corn' } ,
      { id: 53, name: 'Baby Spinach Leaves' } ,
      { id: 54, name: 'Baby-back Ribs' } ,
      { id: 55, name: 'Baby-back Ribs' } ,
      { id: 56, name: 'Bacon' } ,
      { id: 57, name: 'Bacon Fat' } ,
      { id: 58, name: 'Baguette' } ,
      { id: 59, name: 'Baking Bar' } ,
      { id: 60, name: 'Baking Powder' } ,
      { id: 61, name: 'Baking Soda' } ,
      { id: 62, name: 'Balsamic Glaze' } ,
      { id: 63, name: 'Balsamic Vinegar' } ,
      { id: 64, name: 'Bamboo Shoots' } ,
      { id: 65, name: 'Banana' } ,
      { id: 66, name: 'Basmati Rice' } ,
      { id: 67, name: 'Bay Leaves' } ,
      { id: 68, name: 'Bbq Sauce' } ,
      { id: 69, name: 'Beans' } ,
      { id: 70, name: 'Beef' } ,
      { id: 71, name: 'Beef Brisket' } ,
      { id: 72, name: 'Beef Broth' } ,
      { id: 73, name: 'Beef Chuck Roast' } ,
      { id: 74, name: 'Beef Stock' } ,
      { id: 75, name: 'Beef Tenderloin' } ,
      { id: 76, name: 'Beer' } ,
      { id: 77, name: 'Beer' } ,
      { id: 78, name: 'Beets' } ,
      { id: 79, name: 'Bell Pepper' } ,
      { id: 80, name: 'Berries' } ,
      { id: 81, name: 'Biscuit Mix' } ,
      { id: 82, name: 'Biscuits' } ,
      { id: 83, name: 'Bittersweet Chocolate' } ,
      { id: 84, name: 'Black Bean Sauce' } ,
      { id: 85, name: 'Black Beans' } ,
      { id: 86, name: 'Black Olives' } ,
      { id: 87, name: 'Black Pepper' } ,
      { id: 88, name: 'Black Sesame Seeds' } ,
      { id: 89, name: 'Blackberries' } ,
      { id: 90, name: 'Blanched Almonds' } ,
      { id: 91, name: 'Blood Orange' } ,
      { id: 92, name: 'Blue Cheese' } ,
      { id: 93, name: 'Blueberries' } ,
      { id: 94, name: 'Bok Choy' } ,
      { id: 95, name: 'Boneless Skinless Chicken Breast' } ,
      { id: 96, name: 'Bourbon' } ,
      { id: 97, name: 'Brandy' } ,
      { id: 98, name: 'Bread' } ,
      { id: 99, name: 'Bread Flour' } ,
      { id: 100, name: 'Breakfast Links' } ,
      { id: 101, name: 'Brie' } ,
      { id: 102, name: 'Broccoli' } ,
      { id: 103, name: 'Broccoli Florets' } ,
      { id: 104, name: 'Brown Rice' } ,
      { id: 105, name: 'Brown Rice Flour' } ,
      { id: 106, name: 'Brown Sugar' } ,
      { id: 107, name: 'Brownie Mix' } ,
      { id: 108, name: 'Brussel Sprouts' } ,
      { id: 109, name: 'Bulgur' } ,
      { id: 110, name: 'Butter' } ,
      { id: 111, name: 'Butterhead Lettuce' } ,
      { id: 112, name: 'Buttermilk' } ,
      { id: 113, name: 'Butternut Squash' } ,
      { id: 114, name: 'Butterscotch Chips' } ,
      { id: 115, name: 'Cabbage' } ,
      { id: 116, name: 'Caesar Dressing' } ,
      { id: 117, name: 'Cajun Seasoning' } ,
      { id: 118, name: 'Cake Flour' } ,
      { id: 119, name: 'Candy Canes' } ,
      { id: 120, name: 'Candy Coating' } ,
      { id: 121, name: 'Candy Melts' } ,
      { id: 122, name: 'Canned Black Beans' } ,
      { id: 123, name: 'Canned Diced Tomatoes' } ,
      { id: 124, name: 'Canned Garbanzo Beans' } ,
      { id: 125, name: 'Canned Green Chiles' } ,
      { id: 126, name: 'Canned Kidney Beans' } ,
      { id: 127, name: 'Canned Mushrooms' } ,
      { id: 128, name: 'Canned Pinto Beans' } ,
      { id: 129, name: 'Canned Red Kidney Beans' } ,
      { id: 130, name: 'Canned Tomatoes' } ,
      { id: 131, name: 'Canned Tuna' } ,
      { id: 132, name: 'Canned White Beans' } ,
      { id: 133, name: 'Canned White Cannellini Beans' } ,
      { id: 134, name: 'Cannellini Beans' } ,
      { id: 135, name: 'Cantaloupe' } ,
      { id: 136, name: 'Capers' } ,
      { id: 137, name: 'Caramel Sauce' } ,
      { id: 138, name: 'Caramels' } ,
      { id: 139, name: 'Caraway Seed' } ,
      { id: 140, name: 'Cardamom' } ,
      { id: 141, name: 'Cardamom Pods' } ,
      { id: 142, name: 'Carp' } ,
      { id: 143, name: 'Carrots' } ,
      { id: 144, name: 'Cat Fish Filets' } ,
      { id: 145, name: 'Cauliflower' } ,
      { id: 146, name: 'Cauliflower Florets' } ,
      { id: 147, name: 'Cauliflower Rice' } ,
      { id: 148, name: 'Celery' } ,
      { id: 149, name: 'Celery Ribs' } ,
      { id: 150, name: 'Celery Root' } ,
      { id: 151, name: 'Celery Salt' } ,
      { id: 152, name: 'Celery Seed' } ,
      { id: 153, name: 'Cereal' } ,
      { id: 154, name: 'Champagne' } ,
      { id: 155, name: 'Chana Dal' } ,
      { id: 156, name: 'Cheddar' } ,
      { id: 157, name: 'Cheese' } ,
      { id: 158, name: 'Cheese Curds' } ,
      { id: 159, name: 'Cheese Dip' } ,
      { id: 160, name: 'Cheese Soup' } ,
      { id: 161, name: 'Cheese Tortellini' } ,
      { id: 162, name: 'Cherry' } ,
      { id: 163, name: 'Cherry Pie Filling' } ,
      { id: 164, name: 'Cherry Tomatoes' } ,
      { id: 165, name: 'Chestnuts' } ,
      { id: 166, name: 'Chia Seeds' } ,
      { id: 167, name: 'Chicken Base' } ,
      { id: 168, name: 'Chicken Bouillon' } ,
      { id: 169, name: 'Chicken Bouillon Granules' } ,
      { id: 170, name: 'Chicken Breasts' } ,
      { id: 171, name: 'Chicken Broth' } ,
      { id: 172, name: 'Chicken Drumsticks' } ,
      { id: 173, name: 'Chicken Legs' } ,
      { id: 174, name: 'Chicken Pieces' } ,
      { id: 175, name: 'Chicken Sausage' } ,
      { id: 176, name: 'Chicken Stock' } ,
      { id: 177, name: 'Chicken Tenders' } ,
      { id: 178, name: 'Chicken Thighs' } ,
      { id: 179, name: 'Chicken Wings' } ,
      { id: 180, name: 'Chickpea' } ,
      { id: 181, name: 'Chile Garlic Sauce' } ,
      { id: 182, name: 'Chili Paste' } ,
      { id: 183, name: 'Chili Peppers' } ,
      { id: 184, name: 'Chili Powder' } ,
      { id: 185, name: 'Chili Sauce' } ,
      { id: 186, name: 'Chipotle Chiles In Adobo' } ,
      { id: 187, name: 'Chipotle Chilies' } ,
      { id: 188, name: 'Chipotle Peppers In Adobo' } ,
      { id: 189, name: 'Chive & Onion Cream Cheese Spread' } ,
      { id: 190, name: 'Chocolate' } ,
      { id: 191, name: 'Chocolate Chip Cookies' } ,
      { id: 192, name: 'Chocolate Chunks' } ,
      { id: 193, name: 'Chocolate Ice Cream' } ,
      { id: 194, name: 'Chocolate Milk' } ,
      { id: 195, name: 'Chocolate Sandwich Cookies' } ,
      { id: 196, name: 'Chocolate Syrup' } ,
      { id: 197, name: 'Chocolate Wafer Cookies' } ,
      { id: 198, name: 'Chorizo Sausage' } ,
      { id: 199, name: 'Cider Vinegar' } ,
      { id: 200, name: 'Cilantro' } ,
      { id: 201, name: 'Cinnamon Roll' } ,
      { id: 202, name: 'Cinnamon Stick' } ,
      { id: 203, name: 'Cinnamon Sugar' } ,
      { id: 204, name: 'Cinnamon Swirl Bread' } ,
      { id: 205, name: 'Clam Juice' } ,
      { id: 206, name: 'Clams' } ,
      { id: 207, name: 'Clarified Butter' } ,
      { id: 208, name: 'Clove' } ,
      { id: 209, name: 'Coarse Salt' } ,
      { id: 210, name: 'Coarsely Ground Pepper' } ,
      { id: 211, name: 'Cocoa Nibs' } ,
      { id: 212, name: 'Cocoa Powder' } ,
      { id: 213, name: 'Coconut' } ,
      { id: 214, name: 'Coconut Aminos' } ,
      { id: 215, name: 'Coconut Butter' } ,
      { id: 216, name: 'Coconut Cream' } ,
      { id: 217, name: 'Coconut Extract' } ,
      { id: 218, name: 'Coconut Flour' } ,
      { id: 219, name: 'Coconut Milk' } ,
      { id: 220, name: 'Coconut Oil' } ,
      { id: 221, name: 'Coconut Water' } ,
      { id: 222, name: 'Cod' } ,
      { id: 223, name: 'Coffee' } ,
      { id: 224, name: 'Cognac' } ,
      { id: 225, name: 'Cola' } ,
      { id: 226, name: 'Colby Jack' } ,
      { id: 227, name: 'Collard Greens' } ,
      { id: 228, name: 'Condensed Cream Of Celery Soup' } ,
      { id: 229, name: 'Condensed Cream Of Mushroom Soup' } ,
      { id: 230, name: "Confectioner's Swerve" } ,
      { id: 231, name: 'Cooked Bacon' } ,
      { id: 232, name: 'Cooked Brown Rice' } ,
      { id: 233, name: 'Cooked Chicken Breast' } ,
      { id: 234, name: 'Cooked Ham' } ,
      { id: 235, name: 'Cooked Long Grain Rice' } ,
      { id: 236, name: 'Cooked Pasta' } ,
      { id: 237, name: 'Cooked Polenta' } ,
      { id: 238, name: 'Cooked Quinoa' } ,
      { id: 239, name: 'Cooked Wild Rice' } ,
      { id: 240, name: 'Cookies' } ,
      { id: 241, name: 'Coriander' } ,
      { id: 242, name: 'Corn' } ,
      { id: 243, name: 'Corn Bread Mix' } ,
      { id: 244, name: 'Corn Chips' } ,
      { id: 245, name: 'Corn Flakes Cereal' } ,
      { id: 246, name: 'Corn Flour' } ,
      { id: 247, name: 'Corn Kernels' } ,
      { id: 248, name: 'Corn Oil' } ,
      { id: 249, name: 'Corn Tortillas' } ,
      { id: 250, name: 'Cornbread' } ,
      { id: 251, name: 'Corned Beef' } ,
      { id: 252, name: 'Cornish Hens' } ,
      { id: 253, name: 'Cornmeal' } ,
      { id: 254, name: 'Cornstarch' } ,
      { id: 255, name: 'Cotija Cheese' } ,
      { id: 256, name: 'Cottage Cheese' } ,
      { id: 257, name: 'Country Bread' } ,
      { id: 258, name: 'Courgettes' } ,
      { id: 259, name: 'Couscous' } ,
      { id: 260, name: 'Cow Pea' } ,
      { id: 261, name: 'Crabmeat' } ,
      { id: 262, name: 'Cracked Pepper' } ,
      { id: 263, name: 'Cranberries' } ,
      { id: 264, name: 'Cranberry Juice' } ,
      { id: 265, name: 'Cream' } ,
      { id: 266, name: 'Cream Cheese' } ,
      { id: 267, name: 'Cream Cheese Block' } ,
      { id: 268, name: 'Cream Of Chicken Soup' } ,
      { id: 269, name: 'Cream Of Tartar' } ,
      { id: 270, name: 'Creamed Corn' } ,
      { id: 271, name: 'Creamy Peanut Butter' } ,
      { id: 272, name: 'Creme Fraiche' } ,
      { id: 273, name: 'Cremini Mushrooms' } ,
      { id: 274, name: 'Creole Seasoning' } ,
      { id: 275, name: 'Crisp Rice Cereal' } ,
      { id: 276, name: 'Croutons' } ,
      { id: 277, name: 'Crystallized Ginger' } ,
      { id: 278, name: 'Cucumber' } ,
      { id: 279, name: 'Cumin Seeds' } ,
      { id: 280, name: 'Cup Cake' } ,
      { id: 281, name: 'Currants' } ,
      { id: 282, name: 'Curry Leaves' } ,
      { id: 283, name: 'Dairy Free Milk' } ,
      { id: 284, name: 'Dark Brown Sugar' } ,
      { id: 285, name: 'Dark Chocolate' } ,
      { id: 286, name: 'Dark Chocolate Candy Bars' } ,
      { id: 287, name: 'Dark Chocolate Chips' } ,
      { id: 288, name: 'Dark Sesame Oil' } ,
      { id: 289, name: 'Dates' } ,
      { id: 290, name: 'Deep Dish Pie Crust' } ,
      { id: 291, name: 'Deli Ham' } ,
      { id: 292, name: 'Deli Turkey' } ,
      { id: 293, name: 'Dessert Oats' } ,
      { id: 294, name: 'Dessert Wine' } ,
      { id: 295, name: 'Diced Ham' } ,
      { id: 296, name: 'Diet Pop' } ,
      { id: 297, name: 'Dijon Mustard' } ,
      { id: 298, name: 'Dill' } ,
      { id: 299, name: 'Dill Pickles' } ,
      { id: 300, name: 'Hot Dog' } ,
      { id: 301, name: 'Double Cream' } ,
      { id: 302, name: 'Dried Apricots' } ,
      { id: 303, name: 'Dried Basil' } ,
      { id: 304, name: 'Dried Cherries' } ,
      { id: 305, name: 'Dried Chorizo' } ,
      { id: 306, name: 'Dried Cranberries' } ,
      { id: 307, name: 'Dried Dill' } ,
      { id: 308, name: 'Dried Onion' } ,
      { id: 309, name: 'Dried Porcini Mushrooms' } ,
      { id: 310, name: 'Dried Rubbed Sage' } ,
      { id: 311, name: 'Dried Thyme' } ,
      { id: 312, name: 'Dried Tomatoes' } ,
      { id: 313, name: 'Dry Bread Crumbs' } ,
      { id: 314, name: 'Dry Milk' } ,
      { id: 315, name: 'Dry Mustard' } ,
      { id: 316, name: 'Dry Red Wine' } ,
      { id: 317, name: 'Dry Roasted Peanuts' } ,
      { id: 318, name: 'Duck Fat' } ,
      { id: 319, name: 'Dutch Process Cocoa Powder' } ,
      { id: 320, name: 'Edamame' } ,
      { id: 321, name: 'Egg Substitute' } ,
      { id: 322, name: 'Egg Vermicelli' } ,
      { id: 323, name: 'Egg Whites' } ,
      { id: 324, name: 'Egg Yolk' } ,
      { id: 325, name: 'Eggnog' } ,
      { id: 326, name: 'Eggplant' } ,
      { id: 327, name: 'Elbow Macaroni' } ,
      { id: 328, name: 'Enchilada Sauce' } ,
      { id: 329, name: 'English Cucumber' } ,
      { id: 330, name: 'English Muffin' } ,
      { id: 331, name: 'Erythritol' } ,
      { id: 332, name: 'Escarole' } ,
      { id: 333, name: 'Espresso' } ,
      { id: 334, name: 'Evaporated Milk' } ,
      { id: 335, name: 'Extra Firm Tofu' } ,
      { id: 336, name: 'Extra Virgin Olive Oil' } ,
      { id: 337, name: 'Farfalle' } ,
      { id: 338, name: 'Farro' } ,
      { id: 339, name: 'Fat Free Mayo' } ,
      { id: 340, name: 'Fat-free Less-sodium Chicken Broth' } ,
      { id: 341, name: 'Fennel' } ,
      { id: 342, name: 'Fennel Seeds' } ,
      { id: 343, name: 'Fenugreek Leaf' } ,
      { id: 344, name: 'Fenugreek Seeds' } ,
      { id: 345, name: 'Feta Cheese' } ,
      { id: 346, name: 'Fettuccine' } ,
      { id: 347, name: 'Fire Roasted Tomatoes' } ,
      { id: 348, name: 'Fish' } ,
      { id: 349, name: 'Fish Sauce' } ,
      { id: 350, name: 'Fish Stock' } ,
      { id: 351, name: 'Flank Steak' } ,
      { id: 352, name: 'Flax Seeds' } ,
      { id: 353, name: 'Fleur De Sel' } ,
      { id: 354, name: 'Flour' } ,
      { id: 355, name: 'Flour Tortillas' } ,
      { id: 356, name: 'Fontina Cheese' } ,
      { id: 357, name: 'Food Dye' } ,
      { id: 358, name: "Frank's Redhot Sauce" } ,
      { id: 359, name: 'Free Range Eggs' } ,
      { id: 360, name: 'French Bread' } ,
      { id: 361, name: 'Fresh Basil' } ,
      { id: 362, name: 'Fresh Bean Sprouts' } ,
      { id: 363, name: 'Fresh Chives' } ,
      { id: 364, name: 'Fresh Corn' } ,
      { id: 365, name: 'Fresh Corn Kernels' } ,
      { id: 366, name: 'Fresh Figs' } ,
      { id: 367, name: 'Fresh Fruit' } ,
      { id: 368, name: 'Fresh Herbs' } ,
      { id: 369, name: 'Fresh Mint' } ,
      { id: 370, name: 'Fresh Mozzarella' } ,
      { id: 371, name: 'Fresh Rosemary' } ,
      { id: 372, name: 'Fresh Thyme Leaves' } ,
      { id: 373, name: 'Fried Onions' } ,
      { id: 374, name: 'Frosting' } ,
      { id: 375, name: 'Froyo Bars' } ,
      { id: 376, name: 'Frozen Corn' } ,
      { id: 377, name: 'Frozen Spinach' } ,
      { id: 378, name: 'Fudge' } ,
      { id: 379, name: 'Fudge Topping' } ,
      { id: 380, name: 'Fun Size Almond Joy Bar' } ,
      { id: 381, name: 'Garam Masala' } ,
      { id: 382, name: 'Garbanzo Bean Flour' } ,
      { id: 383, name: 'Garlic' } ,
      { id: 384, name: 'Garlic Paste' } ,
      { id: 385, name: 'Garlic Powder' } ,
      { id: 386, name: 'Garlic Powder' } ,
      { id: 387, name: 'Garlic Salt' } ,
      { id: 388, name: 'Gelatin' } ,
      { id: 389, name: 'Gf Chocolate Cake Mix' } ,
      { id: 390, name: 'Gin' } ,
      { id: 391, name: 'Ginger' } ,
      { id: 392, name: 'Ginger Ale' } ,
      { id: 393, name: 'Ginger Paste' } ,
      { id: 394, name: 'Ginger-garlic Paste' } ,
      { id: 395, name: 'Gingersnap Cookies' } ,
      { id: 396, name: 'Gnocchi' } ,
      { id: 397, name: 'Goat Cheese' } ,
      { id: 398, name: 'Golden Raisins' } ,
      { id: 399, name: 'Gorgonzola' } ,
      { id: 400, name: 'Gouda Cheese' } ,
      { id: 401, name: 'Graham Cracker Crumbs' } ,
      { id: 402, name: 'Graham Cracker Pie Crust' } ,
      { id: 403, name: 'Graham Crackers' } ,
      { id: 404, name: 'Grain Blend' } ,
      { id: 405, name: 'Grand Marnier' } ,
      { id: 406, name: 'Granny Smith Apples' } ,
      { id: 407, name: 'Granola' } ,
      { id: 408, name: 'Granulated Garlic' } ,
      { id: 409, name: 'Grape Tomatoes' } ,
      { id: 410, name: 'Grapefruit' } ,
      { id: 411, name: 'Grapeseed Oil' } ,
      { id: 412, name: 'Gravy' } ,
      { id: 413, name: 'Great Northern Beans' } ,
      { id: 414, name: 'Greek Yogurt' } ,
      { id: 415, name: 'Green Beans' } ,
      { id: 416, name: 'Green Bell Pepper' } ,
      { id: 417, name: 'Green Chili Pepper' } ,
      { id: 418, name: 'Green Food Coloring' } ,
      { id: 419, name: 'Green Grapes' } ,
      { id: 420, name: 'Green Olives' } ,
      { id: 421, name: 'Green Onions' } ,
      { id: 422, name: 'Greens' } ,
      { id: 423, name: 'Grill Cheese' } ,
      { id: 424, name: 'Grill Seasoning' } ,
      { id: 425, name: 'Ground Allspice' } ,
      { id: 426, name: 'Ground Ancho Chili' } ,
      { id: 427, name: 'Ground Beef' } ,
      { id: 428, name: 'Ground Chicken' } ,
      { id: 429, name: 'Ground Chipotle Chile Pepper' } ,
      { id: 430, name: 'Ground Cinnamon' } ,
      { id: 431, name: 'Ground Cinnamon' } ,
      { id: 432, name: 'Ground Cloves' } ,
      { id: 433, name: 'Ground Coriander Seeds' } ,
      { id: 434, name: 'Ground Cumin' } ,
      { id: 435, name: 'Ground Flaxseed' } ,
      { id: 436, name: 'Ground Ginger' } ,
      { id: 437, name: 'Ground Lamb' } ,
      { id: 438, name: 'Ground Mace' } ,
      { id: 439, name: 'Ground Nutmeg' } ,
      { id: 440, name: 'Ground Pork' } ,
      { id: 441, name: 'Ground Pork Sausage' } ,
      { id: 442, name: 'Ground Veal' } ,
      { id: 443, name: 'Gruyere' } ,
      { id: 444, name: 'Guacamole' } ,
      { id: 445, name: 'Half N Half' } ,
      { id: 446, name: 'Halibut Fillet' } ,
      { id: 447, name: 'Ham' } ,
      { id: 448, name: 'Hamburger Buns' } ,
      { id: 449, name: 'Hard Cooked Eggs' } ,
      { id: 450, name: 'Harissa' } ,
      { id: 451, name: 'Hash Brown Potatoes' } ,
      { id: 452, name: 'Hazelnuts' } ,
      { id: 453, name: 'Healthy Request Cream Of Celery Soup' } ,
      { id: 454, name: 'Hemp Seeds' } ,
      { id: 455, name: 'Herbes De Provence' } ,
      { id: 456, name: 'Herbs' } ,
      { id: 457, name: "Hershey's Kisses Brand Milk Chocolates" } ,
      { id: 458, name: 'Hoisin Sauce' } ,
      { id: 459, name: 'Honey Mustard' } ,
      { id: 460, name: 'Horseradish' } ,
      { id: 461, name: 'Hot Sauce' } ,
      { id: 462, name: 'Hummus' } ,
      { id: 463, name: 'Ice' } ,
      { id: 464, name: 'Ice Cream' } ,
      { id: 465, name: 'Instant Chocolate Pudding Mix' } ,
      { id: 466, name: 'Instant Coffee Powder' } ,
      { id: 467, name: 'Instant Espresso Powder' } ,
      { id: 468, name: 'Instant Lemon Pudding Mix' } ,
      { id: 469, name: 'Instant Yeast' } ,
      { id: 470, name: 'Irish Cream' } ,
      { id: 471, name: 'Italian Bread' } ,
      { id: 472, name: 'Italian Cheese Blend' } ,
      { id: 473, name: 'Italian Sausages' } ,
      { id: 474, name: 'Italian Seasoning' } ,
      { id: 475, name: 'Jaggery' } ,
      { id: 476, name: 'Jalapeno' } ,
      { id: 477, name: 'Jasmine Rice' } ,
      { id: 478, name: 'Jelly' } ,
      { id: 479, name: 'Jicama' } ,
      { id: 480, name: 'Jimmies' } ,
      { id: 481, name: 'Juice' } ,
      { id: 482, name: 'Jumbo Shell Pasta' } ,
      { id: 483, name: 'Kaffir Lime Leaves' } ,
      { id: 484, name: 'Kahlua' } ,
      { id: 485, name: 'Kalamata Olives' } ,
      { id: 486, name: 'Kale' } ,
      { id: 487, name: 'Ketchup' } ,
      { id: 488, name: 'Kitchen Bouquet' } ,
      { id: 489, name: 'Kiwis' } ,
      { id: 490, name: 'Kosher Salt' } ,
      { id: 491, name: 'Ladyfingers' } ,
      { id: 492, name: 'Lamb' } ,
      { id: 493, name: 'Lasagna Noodles' } ,
      { id: 494, name: 'Lb Cake' } ,
      { id: 495, name: 'Lean Ground Beef' } ,
      { id: 496, name: 'Lean Ground Turkey' } ,
      { id: 497, name: 'Lean Pork Tenderloin' } ,
      { id: 498, name: 'Leeks' } ,
      { id: 499, name: 'Leg Of Lamb' } ,
      { id: 500, name: 'Lemon' } ,
      { id: 501, name: 'Lemon Curd' } ,
      { id: 502, name: 'Lemon Extract' } ,
      { id: 503, name: 'Lemon Juice' } ,
      { id: 504, name: 'Lemon Peel' } ,
      { id: 505, name: 'Lemon Pepper' } ,
      { id: 506, name: 'Lemon Wedges' } ,
      { id: 507, name: 'Lemongrass' } ,
      { id: 508, name: 'Lettuce' } ,
      { id: 509, name: 'Lettuce Leaves' } ,
      { id: 510, name: 'Light Butter' } ,
      { id: 511, name: 'Light Coconut Milk' } ,
      { id: 512, name: 'Light Corn Syrup' } ,
      { id: 513, name: 'Light Cream Cheese' } ,
      { id: 514, name: 'Light Mayonnaise' } ,
      { id: 515, name: 'Light Olive Oil' } ,
      { id: 516, name: 'Light Soy Sauce' } ,
      { id: 517, name: 'Lime' } ,
      { id: 518, name: 'Lime Juice' } ,
      { id: 519, name: 'Lime Wedges' } ,
      { id: 520, name: 'Lime Zest' } ,
      { id: 521, name: 'Linguine' } ,
      { id: 522, name: 'Liquid Smoke' } ,
      { id: 523, name: 'Liquid Stevia' } ,
      { id: 524, name: 'Liquor' } ,
      { id: 525, name: 'Live Lobster' } ,
      { id: 526, name: 'Long-grain Rice' } ,
      { id: 527, name: 'Low Fat Buttermilk' } ,
      { id: 528, name: 'Low Fat Milk' } ,
      { id: 529, name: 'Low Fat Milk' } ,
      { id: 530, name: 'Low Fat Plain Yogurt' } ,
      { id: 531, name: 'Low Fat Ricotta Cheese' } ,
      { id: 532, name: 'Low Fat Sour Cream' } ,
      { id: 533, name: 'Low Sodium Chicken Broth' } ,
      { id: 534, name: 'Low Sodium Soy Sauce' } ,
      { id: 535, name: 'Low-sodium Chicken Stock' } ,
      { id: 536, name: 'Lower Sodium Beef Broth' } ,
      { id: 537, name: 'Lump Crab' } ,
      { id: 538, name: 'M&m Candies' } ,
      { id: 539, name: 'Macadamia Nuts' } ,
      { id: 540, name: 'Macaroni And Cheese Mix' } ,
      { id: 541, name: 'Madras Curry Powder' } ,
      { id: 542, name: 'Malt Drink Mix' } ,
      { id: 543, name: 'Mandarin Orange Sections' } ,
      { id: 544, name: 'Mandarin Oranges' } ,
      { id: 545, name: 'Mango' } ,
      { id: 546, name: 'Maple Syrup' } ,
      { id: 547, name: 'Maraschino Cherries' } ,
      { id: 548, name: 'Margarine' } ,
      { id: 549, name: 'Marinara Sauce' } ,
      { id: 550, name: 'Marjoram' } ,
      { id: 551, name: 'Marsala Wine' } ,
      { id: 552, name: 'Marshmallow Fluff' } ,
      { id: 553, name: 'Marshmallows' } ,
      { id: 554, name: 'Masa Harina' } ,
      { id: 555, name: 'Mascarpone' } ,
      { id: 556, name: 'Mat Beans' } ,
      { id: 557, name: 'Matcha Tea' } ,
      { id: 558, name: 'Mayonnaise' } ,
      { id: 559, name: 'Meat' } ,
      { id: 560, name: 'Meat' } ,
      { id: 561, name: 'Meatballs' } ,
      { id: 562, name: 'Medjool Dates' } ,
      { id: 563, name: 'Mexican Cream' } ,
      { id: 564, name: 'Meyer Lemon Juice' } ,
      { id: 565, name: 'Milk' } ,
      { id: 566, name: 'Milk Chocolate Chips' } ,
      { id: 567, name: 'Mint Chutney' } ,
      { id: 568, name: 'Minute Rice' } ,
      { id: 569, name: 'Miracle Whip' } ,
      { id: 570, name: 'Mirin' } ,
      { id: 571, name: 'Miso' } ,
      { id: 572, name: 'Molasses' } ,
      { id: 573, name: 'Monterey Jack Cheese' } ,
      { id: 574, name: 'Mushroom' } ,
      { id: 575, name: 'Mussels' } ,
      { id: 576, name: 'Mustard' } ,
      { id: 577, name: 'Mustard Seeds' } ,
      { id: 578, name: 'Napa Cabbage' } ,
      { id: 579, name: 'Navel Oranges' } ,
      { id: 580, name: 'Nectarine' } ,
      { id: 581, name: 'New Potatoes' } ,
      { id: 582, name: 'Non-fat Greek Yogurt' } ,
      { id: 583, name: 'Nonfat Cool Whip' } ,
      { id: 584, name: 'Nonfat Milk' } ,
      { id: 585, name: 'Nori' } ,
      { id: 586, name: 'Nut Butter' } ,
      { id: 587, name: 'Nut Meal' } ,
      { id: 588, name: 'Nutella' } ,
      { id: 589, name: 'Nutritional Yeast' } ,
      { id: 590, name: 'Oat Flour' } ,
      { id: 591, name: 'Oats' } ,
      { id: 592, name: 'Oil' } ,
      { id: 593, name: 'Oil Packed Sun Dried Tomatoes' } ,
      { id: 594, name: 'Okra' } ,
      { id: 595, name: 'Old Bay Seasoning' } ,
      { id: 596, name: 'Olive Oil' } ,
      { id: 597, name: 'Olives' } ,
      { id: 598, name: 'Onion' } ,
      { id: 599, name: 'Onion Powder' } ,
      { id: 600, name: 'Onion Soup Mix' } ,
      { id: 601, name: 'Orange' } ,
      { id: 602, name: 'Orange Bell Pepper' } ,
      { id: 603, name: 'Orange Juice' } ,
      { id: 604, name: 'Orange Juice Concentrate' } ,
      { id: 605, name: 'Orange Liqueur' } ,
      { id: 606, name: 'Orange Marmalade' } ,
      { id: 607, name: 'Orange Oil' } ,
      { id: 608, name: 'Orange Zest' } ,
      { id: 609, name: 'Oregano' } ,
      { id: 610, name: 'Oreo Cookies' } ,
      { id: 611, name: 'Orzo' } ,
      { id: 612, name: 'Oyster Sauce' } ,
      { id: 613, name: 'Oysters' } ,
      { id: 614, name: 'Palm Sugar' } ,
      { id: 615, name: 'Pancetta' } ,
      { id: 616, name: 'Paneer' } ,
      { id: 617, name: 'Panko' } ,
      { id: 618, name: 'Papaya' } ,
      { id: 619, name: 'Paprika' } ,
      { id: 620, name: 'Parmigiano Reggiano' } ,
      { id: 621, name: 'Parsley' } ,
      { id: 622, name: 'Parsley Flakes' } ,
      { id: 623, name: 'Parsnip' } ,
      { id: 624, name: 'Part-skim Mozzarella Cheese' } ,
      { id: 625, name: 'Pasta' } ,
      { id: 626, name: 'Pasta Salad Mix' } ,
      { id: 627, name: 'Pasta Sauce' } ,
      { id: 628, name: 'Pastry Flour' } ,
      { id: 629, name: 'Peach' } ,
      { id: 630, name: 'Peanut Butter' } ,
      { id: 631, name: 'Peanut Butter Chips' } ,
      { id: 632, name: 'Peanut Butter Cups' } ,
      { id: 633, name: 'Peanut Oil' } ,
      { id: 634, name: 'Peanuts' } ,
      { id: 635, name: 'Pear Liqueur' } ,
      { id: 636, name: 'Pearl Barley' } ,
      { id: 637, name: 'Pearl Onions' } ,
      { id: 638, name: 'Peas' } ,
      { id: 639, name: 'Pecan' } ,
      { id: 640, name: 'Pecan Pieces' } ,
      { id: 641, name: 'Pecorino' } ,
      { id: 642, name: 'Penne' } ,
      { id: 643, name: 'Peperoncino' } ,
      { id: 644, name: 'Pepper Jack Cheese' } ,
      { id: 645, name: 'Peppercorns' } ,
      { id: 646, name: 'Peppermint Baking Chips' } ,
      { id: 647, name: 'Peppermint Extract' } ,
      { id: 648, name: 'Pepperoni' } ,
      { id: 649, name: 'Peppers' } ,
      { id: 650, name: 'Pesto' } ,
      { id: 651, name: 'Pickle Relish' } ,
      { id: 652, name: 'Pickles' } ,
      { id: 653, name: 'Pico De Gallo' } ,
      { id: 654, name: 'Pie Crust' } ,
      { id: 655, name: 'Pimento Stuffed Olives' } ,
      { id: 656, name: 'Pimientos' } ,
      { id: 657, name: 'Pine Nuts' } ,
      { id: 658, name: 'Pineapple' } ,
      { id: 659, name: 'Pineapple Chunks' } ,
      { id: 660, name: 'Pineapple In Juice' } ,
      { id: 661, name: 'Pineapple Juice' } ,
      { id: 662, name: 'Pink Himalayan Salt' } ,
      { id: 663, name: 'Pinto Beans' } ,
      { id: 664, name: 'Pistachios' } ,
      { id: 665, name: 'Pita' } ,
      { id: 666, name: 'Pizza Crust' } ,
      { id: 667, name: 'Pizza Mix' } ,
      { id: 668, name: 'Plain Greek Yogurt' } ,
      { id: 669, name: 'Plain Nonfat Yogurt' } ,
      { id: 670, name: 'Plain Yogurt' } ,
      { id: 671, name: 'Plantain' } ,
      { id: 672, name: 'Plum' } ,
      { id: 673, name: 'Plum Tomatoes' } ,
      { id: 674, name: 'Poblano Peppers' } ,
      { id: 675, name: 'Polenta' } ,
      { id: 676, name: 'Polish Sausage' } ,
      { id: 677, name: 'Pomegranate Juice' } ,
      { id: 678, name: 'Pomegranate Molasses' } ,
      { id: 679, name: 'Pomegranate Seeds' } ,
      { id: 680, name: 'Popcorn' } ,
      { id: 681, name: 'Poppy Seeds' } ,
      { id: 682, name: 'Pork' } ,
      { id: 683, name: 'Pork & Beans' } ,
      { id: 684, name: 'Pork Belly' } ,
      { id: 685, name: 'Pork Butt' } ,
      { id: 686, name: 'Pork Chops' } ,
      { id: 687, name: 'Pork Links' } ,
      { id: 688, name: 'Pork Loin Chops' } ,
      { id: 689, name: 'Pork Loin Roast' } ,
      { id: 690, name: 'Pork Roast' } ,
      { id: 691, name: 'Pork Shoulder' } ,
      { id: 692, name: 'Pork Tenderloin' } ,
      { id: 693, name: 'Port' } ,
      { id: 694, name: 'Portabella Mushrooms' } ,
      { id: 695, name: 'Pot Roast' } ,
      { id: 696, name: 'Potato Chips' } ,
      { id: 697, name: 'Potato Starch' } ,
      { id: 698, name: 'Potatoes' } ,
      { id: 699, name: 'Poultry Seasoning' } ,
      { id: 700, name: 'Powdered Sugar' } ,
      { id: 701, name: 'Pretzel Sandwiches' } ,
      { id: 702, name: 'Processed American Cheese' } ,
      { id: 703, name: 'Prosciutto' } ,
      { id: 704, name: 'Provolone Cheese' } ,
      { id: 705, name: 'Prunes' } ,
      { id: 706, name: 'Puff Pastry' } ,
      { id: 707, name: 'Pumpkin' } ,
      { id: 708, name: 'Pumpkin Pie Filling' } ,
      { id: 709, name: 'Pumpkin Pie Spice' } ,
      { id: 710, name: 'Pumpkin Puree' } ,
      { id: 711, name: 'Pumpkin Seeds' } ,
      { id: 712, name: 'Queso Fresco' } ,
      { id: 713, name: 'Quick Cooking Oats' } ,
      { id: 714, name: 'Quinoa' } ,
      { id: 715, name: 'Quinoa Flour' } ,
      { id: 716, name: 'Radicchio' } ,
      { id: 717, name: 'Radishes' } ,
      { id: 718, name: 'Raisins' } ,
      { id: 719, name: 'Rajma Masala' } ,
      { id: 720, name: 'Ramen Noodles' } ,
      { id: 721, name: 'Ranch Dressing' } ,
      { id: 722, name: 'Ranch Dressing Mix' } ,
      { id: 723, name: 'Raspberries' } ,
      { id: 724, name: 'Raspberry Jam' } ,
      { id: 725, name: 'Raw Cashews' } ,
      { id: 726, name: 'Raw Shrimp' } ,
      { id: 727, name: 'Ready-to-serve Asian Fried Rice' } ,
      { id: 728, name: 'Real Bacon Recipe Pieces' } ,
      { id: 729, name: 'Red Apples' } ,
      { id: 730, name: 'Red Bell Peppers' } ,
      { id: 731, name: 'Red Cabbage' } ,
      { id: 732, name: 'Red Chilli' } ,
      { id: 733, name: 'Red Delicious Apples' } ,
      { id: 734, name: 'Red Food Coloring' } ,
      { id: 735, name: 'Red Grapefruit Juice' } ,
      { id: 736, name: 'Red Grapes' } ,
      { id: 737, name: 'Red Kidney Beans' } ,
      { id: 738, name: 'Red Lentils' } ,
      { id: 739, name: 'Red Onion' } ,
      { id: 740, name: 'Red Pepper Flakes' } ,
      { id: 741, name: 'Red Pepper Powder' } ,
      { id: 742, name: 'Red Potatoes' } ,
      { id: 743, name: 'Red Velvet Cookie' } ,
      { id: 744, name: 'Red Wine' } ,
      { id: 745, name: 'Red Wine Vinegar' } ,
      { id: 746, name: 'Reduced Fat Shredded Cheddar Cheese' } ,
      { id: 747, name: 'Refried Beans' } ,
      { id: 748, name: 'Refrigerated Crescent Rolls' } ,
      { id: 749, name: 'Refrigerated Pizza Dough' } ,
      { id: 750, name: 'Refrigerated Sugar Cookie Dough' } ,
      { id: 751, name: 'Rhubarb' } ,
      { id: 752, name: 'Rib Tips' } ,
      { id: 753, name: 'Rice' } ,
      { id: 754, name: 'Rice Flour' } ,
      { id: 755, name: 'Rice Krispies Cereal' } ,
      { id: 756, name: 'Rice Milk' } ,
      { id: 757, name: 'Rice Noodles' } ,
      { id: 758, name: 'Rice Paper' } ,
      { id: 759, name: 'Rice Syrup' } ,
      { id: 760, name: 'Rice Vinegar' } ,
      { id: 761, name: 'Rice Wine' } ,
      { id: 762, name: 'Ricotta Salata' } ,
      { id: 763, name: 'Ritz Crackers' } ,
      { id: 764, name: 'Roast Beef' } ,
      { id: 765, name: 'Roasted Chicken' } ,
      { id: 766, name: 'Roasted Nuts' } ,
      { id: 767, name: 'Roasted Peanuts' } ,
      { id: 768, name: 'Roasted Red Peppers' } ,
      { id: 769, name: 'Roma Tomatoes' } ,
      { id: 770, name: 'Romaine Lettuce' } ,
      { id: 771, name: 'Root Vegetables' } ,
      { id: 772, name: 'Rosemary' } ,
      { id: 773, name: 'Rotini Pasta' } ,
      { id: 774, name: 'Rotisserie Chicken' } ,
      { id: 775, name: 'Round Steak' } ,
      { id: 776, name: 'Rub' } ,
      { id: 777, name: 'Rum Extract' } ,
      { id: 778, name: 'Runny Honey' } ,
      { id: 779, name: 'Russet Potatoes' } ,
      { id: 780, name: 'Rutabaga' } ,
      { id: 781, name: 'Rye Bread' } ,
      { id: 782, name: 'Rye Meal' } ,
      { id: 783, name: 'Saffron Threads' } ,
      { id: 784, name: 'Sage' } ,
      { id: 785, name: 'Sage Leaves' } ,
      { id: 786, name: 'Salad Dressing' } ,
      { id: 787, name: 'Salami' } ,
      { id: 788, name: 'Salmon Fillet' } ,
      { id: 789, name: 'Salsa' } ,
      { id: 790, name: 'Salsa Verde' } ,
      { id: 791, name: 'Salt' } ,
      { id: 792, name: 'Salt And Pepper' } ,
      { id: 793, name: 'Salted Butter' } ,
      { id: 794, name: 'Saltine Crackers' } ,
      { id: 795, name: 'Sandwich Bun' } ,
      { id: 796, name: 'Sauerkraut' } ,
      { id: 797, name: 'Sausage' } ,
      { id: 798, name: 'Sausage Links' } ,
      { id: 799, name: 'Scotch Bonnet Chili' } ,
      { id: 800, name: 'Sea Salt' } ,
      { id: 801, name: 'Sea Scallops' } ,
      { id: 802, name: 'Seasoned Bread Crumbs' } ,
      { id: 803, name: 'Seasoned Rice Vinegar' } ,
      { id: 804, name: 'Seasoned Salt' } ,
      { id: 805, name: 'Seasoning' } ,
      { id: 806, name: 'Seasoning Blend' } ,
      { id: 807, name: 'Seeds' } ,
      { id: 808, name: 'Self-rising Flour' } ,
      { id: 809, name: 'Semi Sweet Chocolate Chips' } ,
      { id: 810, name: 'Serrano Chile' } ,
      { id: 811, name: 'Sesame Oil' } ,
      { id: 812, name: 'Sesame Seed Hamburger Buns' } ,
      { id: 813, name: 'Sesame Seeds' } ,
      { id: 814, name: 'Shallot' } ,
      { id: 815, name: 'Sharp Cheddar Cheese' } ,
      { id: 816, name: 'Sheeps Milk Cheese' } ,
      { id: 817, name: 'Shells' } ,
      { id: 818, name: 'Sherry' } ,
      { id: 819, name: 'Sherry' } ,
      { id: 820, name: 'Sherry Vinegar' } ,
      { id: 821, name: 'Shiitake Mushroom Caps' } ,
      { id: 822, name: 'Short Grain Rice' } ,
      { id: 823, name: 'Short Pasta' } ,
      { id: 824, name: 'Short Ribs' } ,
      { id: 825, name: 'Shortbread Cookies' } ,
      { id: 826, name: 'Shortcrust Pastry' } ,
      { id: 827, name: 'Shortening' } ,
      { id: 828, name: 'Shredded Cheddar Cheese' } ,
      { id: 829, name: 'Shredded Cheese' } ,
      { id: 830, name: 'Shredded Chicken' } ,
      { id: 831, name: 'Shredded Coconut' } ,
      { id: 832, name: 'Shredded Mexican Cheese Blend' } ,
      { id: 833, name: 'Shredded Mexican Cheese Blend' } ,
      { id: 834, name: 'Shredded Mozzarella' } ,
      { id: 835, name: 'Silken Tofu' } ,
      { id: 836, name: 'Sirloin Steak' } ,
      { id: 837, name: 'Skim Milk Ricotta' } ,
      { id: 838, name: 'Skim Vanilla Greek Yogurt' } ,
      { id: 839, name: 'Skin-on Bone-in Chicken Leg Quarters' } ,
      { id: 840, name: 'Skinless Boneless Chicken Breast Halves' } ,
      { id: 841, name: 'Skinless Boneless Chicken Thighs' } ,
      { id: 842, name: 'Skinned Black Gram' } ,
      { id: 843, name: 'Slaw Dressing' } ,
      { id: 844, name: 'Slaw Mix' } ,
      { id: 845, name: 'Slivered Almonds' } ,
      { id: 846, name: 'Smoked Paprika' } ,
      { id: 847, name: 'Smoked Salmon' } ,
      { id: 848, name: 'Smoked Sausage' } ,
      { id: 849, name: 'Smooth Peanut Butter' } ,
      { id: 850, name: 'Snapper Fillets' } ,
      { id: 851, name: 'Snow Peas' } ,
      { id: 852, name: 'Soda Water' } ,
      { id: 853, name: 'Sour Cream' } ,
      { id: 854, name: 'Sourdough Bowl' } ,
      { id: 855, name: 'Sourdough Bread' } ,
      { id: 856, name: 'Soy Milk' } ,
      { id: 857, name: 'Soy Protein Powder' } ,
      { id: 858, name: 'Soy Sauce' } ,
      { id: 859, name: 'Spaghetti' } ,
      { id: 860, name: 'Spaghetti Squash' } ,
      { id: 861, name: 'Sparkling Wine' } ,
      { id: 862, name: 'Spelt Flour' } ,
      { id: 863, name: 'Spicy Brown Mustard' } ,
      { id: 864, name: 'Spinach' } ,
      { id: 865, name: 'Sprite' } ,
      { id: 866, name: 'Sprouts' } ,
      { id: 867, name: 'Squash' } ,
      { id: 868, name: 'Sriracha Sauce' } ,
      { id: 869, name: 'Steaks' } ,
      { id: 870, name: 'Steel Cut Oats' } ,
      { id: 871, name: 'Stevia' } ,
      { id: 872, name: 'Stew Meat' } ,
      { id: 873, name: 'Stew Vegetables' } ,
      { id: 874, name: 'Stock' } ,
      { id: 875, name: 'Store-bought Phyllo' } ,
      { id: 876, name: 'Stout' } ,
      { id: 877, name: 'Strawberries' } ,
      { id: 878, name: 'Strawberry Jam' } ,
      { id: 879, name: 'Strawberry Jello' } ,
      { id: 880, name: 'Stuffing' } ,
      { id: 881, name: 'Stuffing Mix' } ,
      { id: 882, name: 'Sub Rolls' } ,
      { id: 883, name: 'Sugar' } ,
      { id: 884, name: 'Sugar Snap Peas' } ,
      { id: 885, name: 'Sugar Syrup' } ,
      { id: 886, name: 'Sukrin Sweetener' } ,
      { id: 887, name: 'Summer Savory' } ,
      { id: 888, name: 'Summer Squash' } ,
      { id: 889, name: 'Sunflower Oil' } ,
      { id: 890, name: 'Sunflower Seeds' } ,
      { id: 891, name: 'Sweet Chilli Sauce' } ,
      { id: 892, name: 'Sweet Onion' } ,
      { id: 893, name: 'Sweet Paprika' } ,
      { id: 894, name: 'Sweet Pickle Juice' } ,
      { id: 895, name: 'Sweet Pickle Relish' } ,
      { id: 896, name: 'Sweet Potato' } ,
      { id: 897, name: 'Sweet Tea' } ,
      { id: 898, name: 'Sweetened Coconut' } ,
      { id: 899, name: 'Sweetened Condensed Milk' } ,
      { id: 900, name: 'Sweetened Shredded Coconut' } ,
      { id: 901, name: 'Swiss Chard' } ,
      { id: 902, name: 'Swiss Cheese' } ,
      { id: 903, name: 'Taco Seasoning Mix' } ,
      { id: 904, name: 'Taco Shells' } ,
      { id: 905, name: 'Tahini' } ,
      { id: 906, name: 'Tamari' } ,
      { id: 907, name: 'Tapioca Flour' } ,
      { id: 908, name: 'Tarragon' } ,
      { id: 909, name: 'Tart Apple' } ,
      { id: 910, name: 'Tea Bags' } ,
      { id: 911, name: 'Tequila' } ,
      { id: 912, name: 'Teriyaki Sauce' } ,
      { id: 913, name: 'Thai Basil' } ,
      { id: 914, name: 'Thai Chiles' } ,
      { id: 915, name: 'Thai Red Curry Paste' } ,
      { id: 916, name: 'Thick-cut Bacon' } ,
      { id: 917, name: 'Tilapia Fillets' } ,
      { id: 918, name: 'Toast' } ,
      { id: 919, name: 'Toffee Bits' } ,
      { id: 920, name: 'Tofu' } ,
      { id: 921, name: 'Tomatillos' } ,
      { id: 922, name: 'Tomato Juice' } ,
      { id: 923, name: 'Tomato Paste' } ,
      { id: 924, name: 'Tomato Puree' } ,
      { id: 925, name: 'Tomato Sauce' } ,
      { id: 926, name: 'Tomato Soup' } ,
      { id: 927, name: 'Tomatoes' } ,
      { id: 928, name: 'Top Blade Steak' } ,
      { id: 929, name: 'Top Round Steak' } ,
      { id: 930, name: 'Top Sirloin' } ,
      { id: 931, name: 'Tortilla' } ,
      { id: 932, name: 'Tortilla Chips' } ,
      { id: 933, name: 'Triple Sec' } ,
      { id: 934, name: 'Truffle Oil' } ,
      { id: 935, name: 'Tuna' } ,
      { id: 936, name: 'Turbinado Sugar' } ,
      { id: 937, name: 'Turkey' } ,
      { id: 938, name: 'Turkey Breast' } ,
      { id: 939, name: 'Turkey Kielbasa' } ,
      { id: 940, name: 'Turmeric' } ,
      { id: 941, name: 'Turnips' } ,
      { id: 942, name: 'Unbleached Flour' } ,
      { id: 943, name: 'Unsalted Butter' } ,
      { id: 944, name: 'Unsmoked Back Bacon' } ,
      { id: 945, name: 'Unsweetened Applesauce' } ,
      { id: 946, name: 'Unsweetened Coconut Milk' } ,
      { id: 947, name: 'Unsweetened Shredded Coconut' } ,
      { id: 948, name: 'Vanilla Bean' } ,
      { id: 949, name: 'Vanilla Bean Paste' } ,
      { id: 950, name: 'Vanilla Essence' } ,
      { id: 951, name: 'Vanilla Extract' } ,
      { id: 952, name: 'Vanilla Frosting' } ,
      { id: 953, name: 'Vanilla Instant Pudding Mix' } ,
      { id: 954, name: 'Vanilla Protein Powder' } ,
      { id: 955, name: 'Vanilla Wafers' } ,
      { id: 956, name: 'Vanilla Yogurt' } ,
      { id: 957, name: 'Vegan Cheese' } ,
      { id: 958, name: 'Vegan Chocolate Chips' } ,
      { id: 959, name: 'Vegan Margarine' } ,
      { id: 960, name: 'Vegetable Broth' } ,
      { id: 961, name: 'Vegetable Oil' } ,
      { id: 962, name: 'Vegetarian Bacon' } ,
      { id: 963, name: 'Vermouth' } ,
      { id: 964, name: 'Vinaigrette' } ,
      { id: 965, name: 'Vinegar' } ,
      { id: 966, name: 'Vodka' } ,
      { id: 967, name: 'Walnuts' } ,
      { id: 968, name: 'Water' } ,
      { id: 969, name: 'Water Chestnuts' } ,
      { id: 970, name: 'Water-packed Tuna' } ,
      { id: 971, name: 'Watercress' } ,
      { id: 972, name: 'Watermelon Chunks' } ,
      { id: 973, name: 'Wheat Bran' } ,
      { id: 974, name: 'Wheat Germ' } ,
      { id: 975, name: 'Whipped Cream' } ,
      { id: 976, name: 'Whipped Topping' } ,
      { id: 977, name: 'Whipping Cream' } ,
      { id: 978, name: 'Whiskey' } ,
      { id: 979, name: 'White Balsamic Vinegar' } ,
      { id: 980, name: 'White Bread' } ,
      { id: 981, name: 'White Cake Mix' } ,
      { id: 982, name: 'White Cheddar' } ,
      { id: 983, name: 'White Chocolate' } ,
      { id: 984, name: 'White Chocolate Chips' } ,
      { id: 985, name: 'White Onion' } ,
      { id: 986, name: 'White Pepper' } ,
      { id: 987, name: 'White Whole Wheat Flour' } ,
      { id: 988, name: 'White Wine' } ,
      { id: 989, name: 'White Wine Vinegar' } ,
      { id: 990, name: 'Whole Allspice Berries' } ,
      { id: 991, name: 'Whole Chicken' } ,
      { id: 992, name: 'Whole Coriander Seeds' } ,
      { id: 993, name: 'Whole Cranberry Sauce' } ,
      { id: 994, name: 'Whole Kernel Corn' } ,
      { id: 995, name: 'Whole Star Anise' } ,
      { id: 996, name: 'Whole Wheat Bread' } ,
      { id: 997, name: 'Whole Wheat Flour' } ,
      { id: 998, name: 'Whole Wheat Tortillas' } ,
      { id: 999, name: 'Whole-grain Mustard' } ,
      { id: 1000, name: 'Wine' } ,
      { id: 1001, name: 'Wine Vinegar' } ,
      { id: 1002, name: 'Winter Squash' } ,
      { id: 1003, name: 'Won Ton Wraps' } ,
      { id: 1004, name: 'Worcestershire Sauce' } ,
      { id: 1005, name: 'Wraps' } ,
      { id: 1006, name: 'Xanthan Gum' } ,
      { id: 1007, name: 'Yeast' } ,
      { id: 1008, name: 'Yellow Bell Pepper' } ,
      { id: 1009, name: 'Yellow Cake Mix' } ,
      { id: 1010, name: 'Yellow Onion' } ,
      { id: 1011, name: 'Yogurt' } ,
      { id: 1012, name: 'Yukon Gold Potato' }
    ]);

  const handleOnSearch = (string, results) => {
    // Triggered when the user types in the search input
    console.log(string, results);
  };

  const handleOnHover = (item) => {
    // Triggered when the user hovers over an item in the suggestions list
    console.log('Item hovered:', item);
  };

  const handleOnSelect = (item) => {
    // Triggered when the user selects an item from the suggestions list
    console.log('Item selected:', item);
    console.log('Passing up a level:', item.name);
    onIngredientSearch(item.name);
  };

  return (
    <div className="search-bar-container">
      <ReactSearchAutocomplete
        items={items}
        placeholder="Enter ingredient ..."
        onSearch={handleOnSearch}
        onHover={handleOnHover}
        onSelect={handleOnSelect}
      />
    </div>
  );
}

export default SearchBar;
